drivers: samsung: debug: Fix implicit function declaration of 'memset_io'
The build environment encountered an error due to the implicit declaration
of 'memset_io' when compiling Samsung debug drivers with `-Werror`:

    error: implicit declaration of function 'memset_io' [-Werror,-Wimplicit-function-declaration]
    ...
    memset_io(secdbg_summary, 0x0, size);

The function `memset_io` is typically used for I/O memory operations and its
prototype is defined in `<linux/io.h>`. Explicitly include this header
file to ensure proper function declaration and fix the build error.